spring:
  profiles:
    active: local
---
server:
  port: 8761

logging:
  level:
    yongs:
      temp: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF
          
spring:
  config:
    activate:
      on-profile: local
  application:
    name: example-eureka

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
server:
  port: 8080
  
spring:
  config:
    activate:
      on-profile: container
  application:
    name: example-eureka

eureka:
  instance:
    preferIpAddress: true
    hostname: example-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
